// swift-tools-version:6.0
// Wraps the Rust staticlib: a binaryTarget (XCFramework) plus the Swift
// generated by uniffi-bindgen-swift. Both are build artefacts written by
// build.sh, never committed.
import PackageDescription

let package = Package(
    name: "CalamoCore",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "CalamoCore", targets: ["CalamoCore"])
    ],
    targets: [
        .binaryTarget(
            name: "CalamoFFI",
            path: "Frameworks/CalamoFFI.xcframework"
        ),
        .target(
            name: "CalamoCore",
            dependencies: ["CalamoFFI"],
            path: "Sources/CalamoCore",
            // Generated sources stay in mode 5; the app targets compile in
            // Swift 6 against their Sendable-annotated interface (J2 audit).
            swiftSettings: [.swiftLanguageMode(.v5)],
            // llama.cpp will be linked statically inside the staticlib; its
            // link directives don't propagate to the Swift executable's
            // linker, so its system frameworks are declared here.
            linkerSettings: [
                .linkedFramework("Foundation"), // ggml-metal is Objective-C
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Accelerate"), // CPU BLAS fallback / vDSP
                .linkedLibrary("c++"), // llama.cpp is C++; rustc won't link it
            ]
        ),
    ]
)
